services:
  pa-env:
    build: . # 使用当前目录的 Dockerfile 构建镜像
    container_name: pa
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./:/root/thss-2025-compiler # 本地目录挂载到容器
      - /Users/erix/.ssh:/root/.ssh
